# Start with the official Node.js image.
FROM node:20.9.0

# Set the working directory in the Docker container.
WORKDIR /app

# Copy the package.json and package-lock.json files (needed for production).
COPY package*.json .

# Copy the application files (needed for production) [except for node_modules].
COPY . .

# Install the application dependencies.
RUN npm install

# The application listens on port 3000, so let's expose it.
EXPOSE 3000

# Define the command to run the application.
CMD [ "npm", "run", "dev" ]